<div id="footer">
  <ul class="address">
    <li>Taylor K. Spencer</li>
    <li>924 Hillside Drive</li>
    <li>Copper Canyon, TX 75077</li>
    <li>Email:&nbsp;<img src="../shared/footer-email-link.png" alt="Email address protected from spambots" onClick="javascript:location.href='mailto:taylorkspencer@gmail.com'" class="emailLink"/></li>
  </ul>
  <ul class="links">
    <li><a href="../">Index</a></li>
    <li><a href="#top">Return to Top</a></li>
  </ul>
  <ul class="copyNotices">
    <li>This site uses <a href="http://gokercebeci.com/dev/f4player">f4player</a> for Flash playback, which is licensed under the GNU GPLv3 License.</li>
    <li>This site uses the fonts Breip, Raleway, Cabin, Old Standard, and Inconsolata.</li>
    <ul>
      <li>Breip is &copy; 2006 Alan Hussey and Adam Breipohl and is licensed under the SIL Open Font License.</li>
      <li>Raleway is &copy; 2010-2013 Matt McInerney, Pablo Impallari, and Rodrigo Fuenzalida and is licensed under the SIL Open Font License.</li>
      <li>Cabin is &copy; 2010-2011 Pablo Impallari and is licensed under the SIL Open Font License.</li>
      <li>Old Standard is &copy; 2006-2011 Alexey Kryukov and is licensed under the SIL Open Font License.</li>
      <li>Inconsolata is &copy; 2006 Raph Levien and is licensed under the SIL Open Font License.</li>
    </ul>
    <li>This site uses Big Buck Bunny in its video player.</li>
    <ul>
      <li>Big Buck Bunny is &copy; 2008 Blender Foundation and is licensed under the Creative Commons Attribution 3.0 License.</li>
    </ul>
    <li>Example on Video+Canvas page adapted from <a href="http://html5doctor.com/video-canvas-magic/">http://html5doctor.com/video-canvas-magic/</a>.</li>
  </ul>
</div>
