<div id="header">
  <a name="top"></a>
  <span class="primary">LTEC 3260 - Assignment 5</span>
  <table id="authorInfoTable">
    <tr>
      <td>Taylor Spencer</td>
      <td>LTEC 3260</td>
      <td>Web Authoring</td>
      <td>Assignment 5</td>
    </tr>
    <tr>
      <td colspan="4">Email:&nbsp;<img src="../shared/header-email-link.png" alt="Email address protected from spambots" onClick="javascript:location.href='mailto:taylorkspencer@gmail.com'" class="emailLink"/></td>
    </tr>
  </table>
</div>
